ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS purchase_price DECIMAL(12, 2);
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS financial_state VARCHAR(50);
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS documentation TEXT;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS conservation TEXT;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS features JSONB DEFAULT '{}';
